### ISSUE TITLE
table index is nil

### ISSUE THREAD

**Issue by MokaNiax** [esx-framework/esx_datastore#6]
[script:esx_datastore] SCRIPT ERROR: @esx_datastore/server/main.lua:18: table index is nil
[script:esx_datastore] > handler (@esx_datastore/server/main.lua:18)
[script:esx_datastore] > rawQuery (@oxmysql/dist/build.js:26449)
[script:esx_datastore] > processTicksAndRejections (node:internal/process/task_queues:96)

**Comment by Gellipapa** [comment]
@MokaNiax Hi! Probably some data in the database is missing and that's why you get nil, datastore is a very old script and we don't want to change it, it's part of a legacy system so if you use the right data it won't throw an error, several addon scripts handle it without errors. 

Ask on discord how you can fix this, it is a unique case.

Thanks.
