### ISSUE TITLE
SCRIPT ERROR: @esx_datastore/server/main.lua:15: attempt to call a nil value (global 'CreateDataStore')

### ISSUE THREAD

**Issue by AmineXTV** [esx-framework/esx_datastore#7]
I have this issue:
[script:esx_datastore] SCRIPT ERROR: @esx_datastore/server/main.lua:15: attempt to call a nil value (global 'CreateDataStore')
[script:esx_datastore] > handler (@esx_datastore/server/main.lua:15)
[script:esx_datastore] > rawQuery (@oxmysql/dist/build.js:27077)
[script:esx_datastore] > processTicksAndRejections (node:internal/process/task_queues:96)

How can i fix it???

**Comment by Gellipapa** [comment]
@AmineXTV Hi! 

It's not clear from this error message which value is nil but since there are 15 rows so many things can't be nil it's worth checking your "datastore_data" table and within that table if you have name and owner if either is missing then delete that row and the system will recreate it or fill the row with data so it's not empty then there will be no nil error. 

It could be caused by a script that registers the store data incorrectly. 

If you look at a recent installation you will not see such an error so this is a unique case and you have to fix it. 

Thank you for your understanding.
